services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_automation
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env_n8n
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - pipelines

volumes:
  n8n_data:
    name: n8n_kevink_n8n_data
