services:
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.png"
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich
    restart: always
networks:
  immich:
    external: true
